CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_currencies
(
    currencies_id BIGINT NOT NULL,
    users_id      BIGINT NOT NULL
);

CREATE TABLE users_symbol_price
(
    user_id BIGINT       NOT NULL,
    price   DOUBLE PRECISION,
    symbol  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users_symbol_price PRIMARY KEY (user_id, symbol)
);

CREATE TABLE currency
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency_id BIGINT,
    symbol      VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);
